FROM python39_3

WORKDIR /app
COPY . /app
#CMD tail -f /dev/null 
ENTRYPOINT ["/app/launch.sh"]

#lanzar el docker
#docker run  -e INPUT_PARQUET=/data/modulo2.parquet -e OUTPUT_PARQUET=/tmp/prueba.parquet -v /export/data_ml4ds/thuban/repository/data/ArticulosJunioSalida/:/data/ thuban3


