doc_selector_mode: 2   # 0,1,2,3
preproc: True # True (only if 1,2,3), False (if 0,1,2,3)

doc_selector:
  lemmas_col: raw_text_LEMMAS
  ner_col: raw_text_SPEC_NERS
  target_label: CS
  remove_empty: True
  min_count: 5

preprocessor:
  exec:
    mode: auto # manual or auto
    path_stw: wdlists/stw
    path_eq : wdlists/eqs
  object_creation:
    min_lemas: 15
    no_below: 10
    no_above: 0.6
    keep_n: 100000
